"""Update firewall models according to feedback

Revision ID: 5a9956d47ae9
Revises: 4aa4a7d31ca6
Create Date: 2025-08-29 00:10:11.980714

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5a9956d47ae9"
down_revision = "4aa4a7d31ca6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filtering_policies", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "unique_name_and_firewall_id", ["name", "firewall_id"]
        )

    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_hash", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("destination_hash", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("port_hash", sa.Integer(), nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_destination_hash"),
            ["destination_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_port_hash"),
            ["port_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_source_hash"),
            ["source_hash"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "unique_filtering_policy_sources_destinations_ports",
            [
                "source_hash",
                "destination_hash",
                "port_hash",
                "filtering_policy_id",
            ],
        )
        batch_op.drop_column("destination_port")
        batch_op.drop_column("destination_address_pattern")
        batch_op.drop_column("source_address_pattern")
        batch_op.drop_column("source_port")

    with op.batch_alter_table("firewalls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewalls_name"))
        batch_op.create_index(
            batch_op.f("ix_firewalls_name"), ["name"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firewalls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewalls_name"))
        batch_op.create_index(
            batch_op.f("ix_firewalls_name"), ["name"], unique=False
        )

    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_port", sa.INTEGER(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("source_address_pattern", sa.VARCHAR(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "destination_address_pattern", sa.VARCHAR(), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("destination_port", sa.INTEGER(), nullable=False)
        )
        batch_op.drop_constraint(
            "unique_filtering_policy_sources_destinations_ports", type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_firewall_rules_source_hash"))
        batch_op.drop_index(batch_op.f("ix_firewall_rules_port_hash"))
        batch_op.drop_index(batch_op.f("ix_firewall_rules_destination_hash"))
        batch_op.drop_column("port_hash")
        batch_op.drop_column("destination_hash")
        batch_op.drop_column("source_hash")

    with op.batch_alter_table("filtering_policies", schema=None) as batch_op:
        batch_op.drop_constraint("unique_name_and_firewall_id", type_="unique")

    # ### end Alembic commands ###
