"""Add index to fields that are included in filters

Revision ID: 8eff3e23cd6f
Revises: 4a1bb7057228
Create Date: 2025-09-01 08:58:17.401652

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8eff3e23cd6f"
down_revision = "4a1bb7057228"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filtering_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_filtering_policies_default_action"),
            ["default_action"],
            unique=False,
        )

    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_action"), ["action"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewall_rules_action"))

    with op.batch_alter_table("filtering_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filtering_policies_default_action"))

    # ### end Alembic commands ###
