"""Add priority to firewall rules

Revision ID: 4a1bb7057228
Revises: 22db49a19cf4
Create Date: 2025-08-31 20:46:30.884632

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a1bb7057228"
down_revision = "22db49a19cf4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.add_column(sa.Column("priority", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("description", sa.String(), nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_priority"), ["priority"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewall_rules_priority"))
        batch_op.drop_column("description")
        batch_op.drop_column("priority")

    # ### end Alembic commands ###
