"""Update firewall models according to feedback

Revision ID: 22db49a19cf4
Revises: 4aa4a7d31ca6
Create Date: 2025-08-31 18:44:37.752482

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "22db49a19cf4"
down_revision = "4aa4a7d31ca6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "firewall_rule_destinations",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("firewall_rule_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["firewall_rule_id"], ["firewall_rules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "firewall_rule_destinations", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_destinations_address"),
            ["address"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_destinations_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_destinations_deleted_at"),
            ["deleted_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_destinations_firewall_rule_id"),
            ["firewall_rule_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_destinations_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_destinations_port"),
            ["port"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_destinations_updated_at"),
            ["updated_at"],
            unique=False,
        )

    op.create_table(
        "firewall_rule_ports",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("firewall_rule_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["firewall_rule_id"], ["firewall_rules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("firewall_rule_ports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_ports_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_ports_deleted_at"),
            ["deleted_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_ports_firewall_rule_id"),
            ["firewall_rule_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_ports_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_ports_number"),
            ["number"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_ports_updated_at"),
            ["updated_at"],
            unique=False,
        )

    op.create_table(
        "firewall_rule_sources",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("firewall_rule_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["firewall_rule_id"], ["firewall_rules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("firewall_rule_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_sources_address"),
            ["address"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_sources_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_sources_deleted_at"),
            ["deleted_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_sources_firewall_rule_id"),
            ["firewall_rule_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_sources_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_sources_port"), ["port"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rule_sources_updated_at"),
            ["updated_at"],
            unique=False,
        )

    with op.batch_alter_table("filtering_policies", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "unique_name_and_firewall_id", ["name", "firewall_id"]
        )

    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_hash", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("destination_hash", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("port_hash", sa.Integer(), nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_destination_hash"),
            ["destination_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_port_hash"),
            ["port_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_source_hash"),
            ["source_hash"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "unique_filtering_policy_action_sources_destinations_ports",
            [
                "source_hash",
                "destination_hash",
                "port_hash",
                "action",
                "filtering_policy_id",
            ],
        )
        batch_op.drop_column("destination_address_pattern")
        batch_op.drop_column("destination_port")
        batch_op.drop_column("source_address_pattern")
        batch_op.drop_column("source_port")

    with op.batch_alter_table("firewalls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewalls_name"))
        batch_op.create_index(
            batch_op.f("ix_firewalls_name"), ["name"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firewalls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewalls_name"))
        batch_op.create_index(
            batch_op.f("ix_firewalls_name"), ["name"], unique=False
        )

    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_port", sa.INTEGER(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("source_address_pattern", sa.VARCHAR(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("destination_port", sa.INTEGER(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "destination_address_pattern", sa.VARCHAR(), nullable=False
            )
        )
        batch_op.drop_constraint(
            "unique_filtering_policy_action_sources_destinations_ports",
            type_="unique",
        )
        batch_op.drop_index(batch_op.f("ix_firewall_rules_source_hash"))
        batch_op.drop_index(batch_op.f("ix_firewall_rules_port_hash"))
        batch_op.drop_index(batch_op.f("ix_firewall_rules_destination_hash"))
        batch_op.drop_column("port_hash")
        batch_op.drop_column("destination_hash")
        batch_op.drop_column("source_hash")

    with op.batch_alter_table("filtering_policies", schema=None) as batch_op:
        batch_op.drop_constraint("unique_name_and_firewall_id", type_="unique")

    with op.batch_alter_table("firewall_rule_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewall_rule_sources_updated_at"))
        batch_op.drop_index(batch_op.f("ix_firewall_rule_sources_port"))
        batch_op.drop_index(batch_op.f("ix_firewall_rule_sources_id"))
        batch_op.drop_index(
            batch_op.f("ix_firewall_rule_sources_firewall_rule_id")
        )
        batch_op.drop_index(batch_op.f("ix_firewall_rule_sources_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_firewall_rule_sources_created_at"))
        batch_op.drop_index(batch_op.f("ix_firewall_rule_sources_address"))

    op.drop_table("firewall_rule_sources")
    with op.batch_alter_table("firewall_rule_ports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewall_rule_ports_updated_at"))
        batch_op.drop_index(batch_op.f("ix_firewall_rule_ports_number"))
        batch_op.drop_index(batch_op.f("ix_firewall_rule_ports_id"))
        batch_op.drop_index(
            batch_op.f("ix_firewall_rule_ports_firewall_rule_id")
        )
        batch_op.drop_index(batch_op.f("ix_firewall_rule_ports_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_firewall_rule_ports_created_at"))

    op.drop_table("firewall_rule_ports")
    with op.batch_alter_table(
        "firewall_rule_destinations", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_firewall_rule_destinations_updated_at")
        )
        batch_op.drop_index(batch_op.f("ix_firewall_rule_destinations_port"))
        batch_op.drop_index(batch_op.f("ix_firewall_rule_destinations_id"))
        batch_op.drop_index(
            batch_op.f("ix_firewall_rule_destinations_firewall_rule_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_firewall_rule_destinations_deleted_at")
        )
        batch_op.drop_index(
            batch_op.f("ix_firewall_rule_destinations_created_at")
        )
        batch_op.drop_index(batch_op.f("ix_firewall_rule_destinations_address"))

    op.drop_table("firewall_rule_destinations")
    # ### end Alembic commands ###
