"""add_firewall_models

Revision ID: 4aa4a7d31ca6
Revises:
Create Date: 2025-08-26 22:56:35.649271

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4aa4a7d31ca6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "firewalls",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("firewalls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_firewalls_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewalls_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewalls_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewalls_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewalls_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "filtering_policies",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "default_action",
            sa.Enum("ALLOW", "DENY", name="firewallaction"),
            nullable=False,
        ),
        sa.Column("firewall_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["firewall_id"], ["firewalls.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("filtering_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_filtering_policies_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_filtering_policies_deleted_at"),
            ["deleted_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_filtering_policies_firewall_id"),
            ["firewall_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_filtering_policies_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_filtering_policies_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_filtering_policies_updated_at"),
            ["updated_at"],
            unique=False,
        )

    op.create_table(
        "firewall_rules",
        sa.Column("source_address_pattern", sa.String(), nullable=False),
        sa.Column("source_port", sa.Integer(), nullable=False),
        sa.Column("destination_address_pattern", sa.String(), nullable=False),
        sa.Column("destination_port", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("ALLOW", "DENY", name="firewallaction"),
            nullable=False,
        ),
        sa.Column("filtering_policy_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["filtering_policy_id"],
            ["filtering_policies.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_deleted_at"),
            ["deleted_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_filtering_policy_id"),
            ["filtering_policy_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_firewall_rules_updated_at"),
            ["updated_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firewall_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewall_rules_updated_at"))
        batch_op.drop_index(batch_op.f("ix_firewall_rules_id"))
        batch_op.drop_index(batch_op.f("ix_firewall_rules_filtering_policy_id"))
        batch_op.drop_index(batch_op.f("ix_firewall_rules_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_firewall_rules_created_at"))

    op.drop_table("firewall_rules")
    with op.batch_alter_table("filtering_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filtering_policies_updated_at"))
        batch_op.drop_index(batch_op.f("ix_filtering_policies_name"))
        batch_op.drop_index(batch_op.f("ix_filtering_policies_id"))
        batch_op.drop_index(batch_op.f("ix_filtering_policies_firewall_id"))
        batch_op.drop_index(batch_op.f("ix_filtering_policies_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_filtering_policies_created_at"))

    op.drop_table("filtering_policies")
    with op.batch_alter_table("firewalls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_firewalls_updated_at"))
        batch_op.drop_index(batch_op.f("ix_firewalls_name"))
        batch_op.drop_index(batch_op.f("ix_firewalls_id"))
        batch_op.drop_index(batch_op.f("ix_firewalls_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_firewalls_created_at"))

    op.drop_table("firewalls")
    # ### end Alembic commands ###
