replicaCount: 1

image:
  repository: fireflow
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 80

resources: { }

livenessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  failureThreshold: 3
  httpGet:
    path: /health/
    port: http
    httpHeaders:
      - name: Authorization
        value: Bearer test
readinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  httpGet:
    path: /health/
    port: http
    httpHeaders:
      - name: Authorization
        value: Bearer test
startupProbe:
  failureThreshold: 60
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1
  httpGet:
    path: /health/
    port: http
    httpHeaders:
      - name: Authorization
        value: Bearer test


volumes: [ ]
volumeMounts: [ ]


nodeSelector: { }

tolerations: [ ]

affinity: { }

db:
  migrationCommand: [ "flask", "db", "upgrade" ]
